version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 
    depends_on:
      - db
      - redis 
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
     - 5432:5432  
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    container_name: postgres_container

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"

