apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: loadimpact/k6:latest
        command: ["k6", "run", "/scripts/averageload.js"]
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: k6-scripts
  backoffLimit: 0